#!/bin/bash

#DEBHELPER#

# postrm script for plamsa-modified-defaults-mx

#set -e

case "$1" in
  purge|remove) dpkg-divert --quiet                                               \
                               --remove                                                 \
                               --package desktop-defaults-mx-kde            \
                               --rename                              \
                               --divert /etc/xdg/kcm-about-distrorc.dpkg-distrib \
								/etc/xdg/kcm-about-distrorc
								
                   ;;

                *) :
                   ;;
esac 

exit 0
