#!/bin/bash

#DEBHELPER#

# preinst script for desktop-defaults-kde-mx

#set -e

mkdir -p /var/lib/dpkg-diverts-mx/etc/grub.d /var/lib/dpkg-diverts-mx/etc/sddm
case "$1" in
  install|upgrade)  dpkg-divert --quiet                                               \
                               --add                                                 \
                               --package desktop-defaults-mx-kde            \
                               --rename                              \
                               --divert /etc/xdg/kcm-about-distrorc.dpkg-distrib \
								/etc/xdg/kcm-about-distrorc
								
				    dpkg-divert --quiet                                               \
                               --add                                                 \
                               --package desktop-defaults-mx-kde            \
                               --rename                              \
                               --divert /var/lib/dpkg-diverts-mx/etc/sddm/wayland-session \
								/etc/sddm/wayland-session
								
								#if files don't exist in divert folder, copy some over so at least some are present
    							if [ -e /etc/sddm/wayland-session ]; then
    								if [ ! -e /var/lib/dpkg-diverts-mx/etc/sddm/wayland-session ]; then
    									mv -f /etc/sddm/wayland-session /var/lib/dpkg-diverts-mx/sddm
    								fi
    							fi
								
                   ;;

                *) :
                   ;;
esac 

exit 0
